### PR TITLE
added golint to build

### PR DESCRIPTION
**Pull request by rkoval**
the build will now fail if golint finds any linting errors with the
project

### CODE REVIEW

**Comment by rkoval** [comment]
oooh, golint requires go 1.6, and our circle-ci ubuntu image is on 12.04, which uses go 1.5 by default. we would need to update our circle-ci image to allow these changes to come in.

@fjordan do you see any problems with updating the circle-ci ubuntu version, and thus the go version for this project? it doesn't look like the project has any documented supported go versions anywhere, but i'm not sure if we'll want to introduce this breaking version change.

**Comment by fjordan** [comment]
@rkoval no problems of which I am aware. Go right ahead. Is there any way we can upgrade it to 1.7?

**Comment by rkoval** [comment]
@fjordan we would need to install go 1.7 manually in the circle.yml file if we wanted that in our build. [circle-ci has no official support for it](https://circleci.com/docs/language-go/#version) as of this time

**Comment by rkoval** [comment]
also, the build is failing because some of some data race?

**Comment by fjordan** [comment]
Thanks @rkoval!

**Pull request merged**
